# Generated by Django 4.2 on 2023-06-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mypatient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=50)),
                ("height", models.CharField(max_length=20)),
                ("weight", models.CharField(blank=True, max_length=50)),
                ("blood_type", models.CharField(max_length=20, null=True)),
                ("last_visit", models.CharField(max_length=20, null=True)),
                ("memo", models.CharField(max_length=500, null=True)),
                (
                    "picture_url",
                    models.ImageField(max_length=150, null=True, upload_to=""),
                ),
            ],
        ),
    ]
